name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the commit
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven and publish to GitHub Packages
        run: mvn -B clean deploy
      - name: Publish code coverage report to Coveralls
        run: mvn -B coveralls:report -D repoToken=${{ secrets.COVERALLS_API_TOKEN }}
